esphome:
  name: esp-pasek-led

esp8266:
  board: esp01_1m

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  password: "xxx"

wifi:
  ssid: "xxx"
  password: "xxx"
  domain: .home

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esp-Pasek-Led Fallback Hotspot"
    password: "xxx"

captive_portal:

output:
  - platform: esp8266_pwm
    pin: GPIO05
    id: red_led
  - platform: esp8266_pwm
    pin: GPIO12
    id: blue_led
  - platform: esp8266_pwm
    pin: GPIO14
    id: green_led
  - platform: esp8266_pwm
    pin: GPIO13
    id: white_led

light:
  - platform: rgbw
    name: "Pasek LED"
    red: red_led
    green: green_led
    blue: blue_led
    white: white_led
